name: Good CI

on: # Ограничение триггеров только необходимыми ветками     
  push:
    branches:
      - main 
      - devops-lab-3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Использование актуальной версии экшена

      - name: Setup Python
        uses: actions/setup-python@v4  # Использование актуальной версии экшена
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3  # Кэширование зависимостей
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('devops/lab_3/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (venv)
        # Использование виртуального окружения
        run: |
          python -m venv venv  
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r devops/lab_3/requirements.txt

      - name: Run tests
        # Тесты теперь обязательно должны завершиться успешно
        run: |
          source venv/bin/activate
          pytest

      - name: Build artifact
        run: |
          mkdir -p build
          echo "Build artifact content" > build/artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Отдельный job, зависимый от успешного завершения build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-build
          path: build/

      - name: Deploy
        env:
          SECRET: ${{ secrets.MY_APP_SECRET }}  # Использование секретов GitHub
        run: |
          echo "Deploying to production with SECRET=${SECRET}"